# database ?? ??
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springboot?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password:
  thymeleaf:
    cache: false

  # spring data jpa ??
  jpa:
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL57Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        type: trace

jwt:
  secret: 64461201e1af406da538b9c48d801312213f591424asd2sa2
  expiration: 3600




