spring:
  mvc:
    throw-exception-if-no-handler-found: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    Docker 설정시
    #    url: jdbc:mysql://mysql_db:3306/${MYSQL_DATABASE}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    #    username: ${SPRING_DATASOURCE_USERNAME}
    #    password: ${SPRING_DATASOURCE_PASSWORD}
    url: jdbc:mysql://localhost:3306/springboot?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 924498
  thymeleaf:
    cache: false

  jpa:
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL57Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
  web:
    resources:
      add-mappings: false

logging:
  level:
    org:
      hibernate:
        type: trace

jwt:
  secret: 64461201e1af406da538b9c48d801312213f591424asd2sa2
  expiration: 3600
  refreshExpiration: 1209600




